version: "3.8"

services:
  uptime-pulse:
    container_name: uptime-pulse-dev
    image: louislam/uptime-pulse:nightly2
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001" # <Host Port>:<Container Port>
      - "3307:3306"
